# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1075, 793)
        Form.setMinimumSize(QtCore.QSize(959, 0))
        self.SeqDir = QtWidgets.QPushButton(Form)
        self.SeqDir.setGeometry(QtCore.QRect(40, 22, 100, 40))
        self.SeqDir.setObjectName("SeqDir")
        self.bmp2png = QtWidgets.QPushButton(Form)
        self.bmp2png.setGeometry(QtCore.QRect(150, 20, 100, 40))
        self.bmp2png.setObjectName("bmp2png")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SeqDir.setText(_translate("Form", "Select Sequence"))
        self.bmp2png.setText(_translate("Form", "Convert to .bmp"))
